blog_posts = [
    {
        'title': 'The ongoing war with Artificial Intelligence',
        'author': 'Jon Snow',
        'content': '''Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent sit amet cursus lorem. Vestibulum massa tortor, fermentum et suscipit in, consectetur id nunc. Pellentesque ut odio cursus, varius neque ac, luctus felis. Duis vel nunc id erat condimentum interdum in nec velit. Aenean pharetra et risus vel consectetur. Suspendisse dignissim vehicula justo, non sodales felis dictum tincidunt. Phasellus faucibus diam ut mi euismod, ut aliquet lacus tincidunt. Phasellus a justo pharetra, accumsan lacus nec, laoreet diam. Donec vehicula ornare urna, eget imperdiet neque efficitur in. Nullam dolor metus, congue eget velit ut, dapibus dignissim nisl. Nullam varius in risus non faucibus.Quisque maximus erat id tristique vestibulum. Fusce eget ultrices sem, et egestas nibh. Pellentesque dignissim dui vel dui fringilla fringilla lobortis in tellus. Pellentesque egestas volutpat nulla, ut rhoncus velit. Phasellus molestie ligula nec pharetra feugiat. Suspendisse accumsan, ligula vel egestas pretium, arcu quam pulvinar turpis, et interdum est sapien sed augue. Duis in dictum nunc, et molestie metus. Aliquam erat volutpat. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;
                      Maecenas rhoncus, magna non facilisis luctus, enim ipsum cursus felis, ac rhoncus nulla massa a mi. Mauris placerat enim malesuada elit ultricies, a faucibus tortor efficitur. Ut quis purus eu augue tincidunt sodales. Suspendisse gravida id purus condimentum vehicula. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nullam nunc augue, pharetra ut libero non, facilisis rutrum nisi. Duis eget cursus ex, id malesuada justo. Vivamus eget massa tincidunt, vehicula enim ac, viverra nisi. Phasellus vulputate tellus felis, non tempor ligula facilisis quis. Pellentesque tincidunt iaculis enim, sit amet tristique libero finibus a. Etiam dui turpis, sagittis vestibulum interdum non, mollis id lorem. In non nisl ex. In eu ante ipsum. Curabitur fermentum a odio in lacinia. Integer rhoncus libero at odio rhoncus, ac ornare metus elementum. Fusce placerat porta felis, consectetur dictum nisl malesuada vitae.
                      Donec facilisis sapien libero. Duis nec varius ante. Duis non massa malesuada, iaculis erat eget, pretium leo. Nulla scelerisque volutpat turpis. In blandit ultricies nunc, ac finibus mauris feugiat porttitor. Integer pulvinar eros eu massa faucibus, nec rhoncus urna vestibulum. Nulla felis lectus, maximus ac viverra in, condimentum at felis. Donec vitae sodales nisi, sit amet efficitur risus. Vestibulum at finibus erat. Donec ante arcu, congue ut malesuada ut, fermentum ac ante. Morbi tristique condimentum sapien eget lobortis. Aenean pharetra pulvinar mauris, nec euismod neque accumsan non. Nulla sagittis leo quis diam lobortis auctor.
                      Aenean rhoncus vehicula lorem vel egestas. Nunc volutpat dui ac lacus lobortis, vitae tincidunt ipsum condimentum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vestibulum interdum ex lectus, sed aliquam dui pellentesque vitae. Vivamus vehicula convallis ultrices. Praesent eleifend, orci ac hendrerit cursus, ante lorem egestas erat, aliquam pulvinar lorem purus a elit. Fusce placerat urna fringilla mattis luctus. Aenean viverra porttitor lacus, quis placerat purus fermentum et. Pellentesque ac enim convallis, mattis eros id, finibus dui. Integer facilisis metus id consectetur tristique. Morbi semper urna pretium, finibus odio at, dapibus tellus. Aliquam commodo vitae quam ac bibendum. Quisque at neque pharetra, mollis ante a, faucibus massa. Ut accumsan, elit malesuada eleifend egestas, tortor erat blandit lorem, nec molestie dui nibh in sapien. In hac habitasse platea dictumst.''',                      
        'permalink': 'artificial-intelligence',
        'tags': 'artificial intelligence, programmer, AI'
    },
    {
        'title': 'How can we govern a multi-planet world?',
        'author': 'Guardians of galaxy',
        'content': '''Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent sit amet cursus lorem. Vestibulum massa tortor, fermentum et suscipit in, consectetur id nunc. Pellentesque ut odio cursus, varius neque ac, luctus felis. Duis vel nunc id erat condimentum interdum in nec velit. Aenean pharetra et risus vel consectetur. Suspendisse dignissim vehicula justo, non sodales felis dictum tincidunt. Phasellus faucibus diam ut mi euismod, ut aliquet lacus tincidunt. Phasellus a justo pharetra, accumsan lacus nec, laoreet diam. Donec vehicula ornare urna, eget imperdiet neque efficitur in. Nullam dolor metus, congue eget velit ut, dapibus dignissim nisl. Nullam varius in risus non faucibus.Quisque maximus erat id tristique vestibulum. Fusce eget ultrices sem, et egestas nibh. Pellentesque dignissim dui vel dui fringilla fringilla lobortis in tellus. Pellentesque egestas volutpat nulla, ut rhoncus velit. Phasellus molestie ligula nec pharetra feugiat. Suspendisse accumsan, ligula vel egestas pretium, arcu quam pulvinar turpis, et interdum est sapien sed augue. Duis in dictum nunc, et molestie metus. Aliquam erat volutpat. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;
                      Maecenas rhoncus, magna non facilisis luctus, enim ipsum cursus felis, ac rhoncus nulla massa a mi. Mauris placerat enim malesuada elit ultricies, a faucibus tortor efficitur. Ut quis purus eu augue tincidunt sodales. Suspendisse gravida id purus condimentum vehicula. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nullam nunc augue, pharetra ut libero non, facilisis rutrum nisi. Duis eget cursus ex, id malesuada justo. Vivamus eget massa tincidunt, vehicula enim ac, viverra nisi. Phasellus vulputate tellus felis, non tempor ligula facilisis quis. Pellentesque tincidunt iaculis enim, sit amet tristique libero finibus a. Etiam dui turpis, sagittis vestibulum interdum non, mollis id lorem. In non nisl ex. In eu ante ipsum. Curabitur fermentum a odio in lacinia. Integer rhoncus libero at odio rhoncus, ac ornare metus elementum. Fusce placerat porta felis, consectetur dictum nisl malesuada vitae.
                      Donec facilisis sapien libero. Duis nec varius ante. Duis non massa malesuada, iaculis erat eget, pretium leo. Nulla scelerisque volutpat turpis. In blandit ultricies nunc, ac finibus mauris feugiat porttitor. Integer pulvinar eros eu massa faucibus, nec rhoncus urna vestibulum. Nulla felis lectus, maximus ac viverra in, condimentum at felis. Donec vitae sodales nisi, sit amet efficitur risus. Vestibulum at finibus erat. Donec ante arcu, congue ut malesuada ut, fermentum ac ante. Morbi tristique condimentum sapien eget lobortis. Aenean pharetra pulvinar mauris, nec euismod neque accumsan non. Nulla sagittis leo quis diam lobortis auctor.
                      Aenean rhoncus vehicula lorem vel egestas. Nunc volutpat dui ac lacus lobortis, vitae tincidunt ipsum condimentum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vestibulum interdum ex lectus, sed aliquam dui pellentesque vitae. Vivamus vehicula convallis ultrices. Praesent eleifend, orci ac hendrerit cursus, ante lorem egestas erat, aliquam pulvinar lorem purus a elit. Fusce placerat urna fringilla mattis luctus. Aenean viverra porttitor lacus, quis placerat purus fermentum et. Pellentesque ac enim convallis, mattis eros id, finibus dui. Integer facilisis metus id consectetur tristique. Morbi semper urna pretium, finibus odio at, dapibus tellus. Aliquam commodo vitae quam ac bibendum. Quisque at neque pharetra, mollis ante a, faucibus massa. Ut accumsan, elit malesuada eleifend egestas, tortor erat blandit lorem, nec molestie dui nibh in sapien. In hac habitasse platea dictumst.''',
        'permalink': 'alien-world',
        'tags': 'solar system, aliens, universe'
    },
    {
        'title': 'Getting started with web development',
        'author': 'Spiderman',
        'content': '''Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent sit amet cursus lorem. Vestibulum massa tortor, fermentum et suscipit in, consectetur id nunc. Pellentesque ut odio cursus, varius neque ac, luctus felis. Duis vel nunc id erat condimentum interdum in nec velit. Aenean pharetra et risus vel consectetur. Suspendisse dignissim vehicula justo, non sodales felis dictum tincidunt. Phasellus faucibus diam ut mi euismod, ut aliquet lacus tincidunt. Phasellus a justo pharetra, accumsan lacus nec, laoreet diam. Donec vehicula ornare urna, eget imperdiet neque efficitur in. Nullam dolor metus, congue eget velit ut, dapibus dignissim nisl. Nullam varius in risus non faucibus.Quisque maximus erat id tristique vestibulum. Fusce eget ultrices sem, et egestas nibh. Pellentesque dignissim dui vel dui fringilla fringilla lobortis in tellus. Pellentesque egestas volutpat nulla, ut rhoncus velit. Phasellus molestie ligula nec pharetra feugiat. Suspendisse accumsan, ligula vel egestas pretium, arcu quam pulvinar turpis, et interdum est sapien sed augue. Duis in dictum nunc, et molestie metus. Aliquam erat volutpat. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;
                      Maecenas rhoncus, magna non facilisis luctus, enim ipsum cursus felis, ac rhoncus nulla massa a mi. Mauris placerat enim malesuada elit ultricies, a faucibus tortor efficitur. Ut quis purus eu augue tincidunt sodales. Suspendisse gravida id purus condimentum vehicula. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nullam nunc augue, pharetra ut libero non, facilisis rutrum nisi. Duis eget cursus ex, id malesuada justo. Vivamus eget massa tincidunt, vehicula enim ac, viverra nisi. Phasellus vulputate tellus felis, non tempor ligula facilisis quis. Pellentesque tincidunt iaculis enim, sit amet tristique libero finibus a. Etiam dui turpis, sagittis vestibulum interdum non, mollis id lorem. In non nisl ex. In eu ante ipsum. Curabitur fermentum a odio in lacinia. Integer rhoncus libero at odio rhoncus, ac ornare metus elementum. Fusce placerat porta felis, consectetur dictum nisl malesuada vitae.
                      Donec facilisis sapien libero. Duis nec varius ante. Duis non massa malesuada, iaculis erat eget, pretium leo. Nulla scelerisque volutpat turpis. In blandit ultricies nunc, ac finibus mauris feugiat porttitor. Integer pulvinar eros eu massa faucibus, nec rhoncus urna vestibulum. Nulla felis lectus, maximus ac viverra in, condimentum at felis. Donec vitae sodales nisi, sit amet efficitur risus. Vestibulum at finibus erat. Donec ante arcu, congue ut malesuada ut, fermentum ac ante. Morbi tristique condimentum sapien eget lobortis. Aenean pharetra pulvinar mauris, nec euismod neque accumsan non. Nulla sagittis leo quis diam lobortis auctor.
                      Aenean rhoncus vehicula lorem vel egestas. Nunc volutpat dui ac lacus lobortis, vitae tincidunt ipsum condimentum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vestibulum interdum ex lectus, sed aliquam dui pellentesque vitae. Vivamus vehicula convallis ultrices. Praesent eleifend, orci ac hendrerit cursus, ante lorem egestas erat, aliquam pulvinar lorem purus a elit. Fusce placerat urna fringilla mattis luctus. Aenean viverra porttitor lacus, quis placerat purus fermentum et. Pellentesque ac enim convallis, mattis eros id, finibus dui. Integer facilisis metus id consectetur tristique. Morbi semper urna pretium, finibus odio at, dapibus tellus. Aliquam commodo vitae quam ac bibendum. Quisque at neque pharetra, mollis ante a, faucibus massa. Ut accumsan, elit malesuada eleifend egestas, tortor erat blandit lorem, nec molestie dui nibh in sapien. In hac habitasse platea dictumst.''',
        'permalink': 'web-development',
        'tags': 'web devleopment, web'
    },
    {
        'title':'Getting started with flask framework',
        'author': 'Panda',
        'content': '''Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent sit amet cursus lorem. Vestibulum massa tortor, fermentum et suscipit in, consectetur id nunc. Pellentesque ut odio cursus, varius neque ac, luctus felis. Duis vel nunc id erat condimentum interdum in nec velit. Aenean pharetra et risus vel consectetur. Suspendisse dignissim vehicula justo, non sodales felis dictum tincidunt. Phasellus faucibus diam ut mi euismod, ut aliquet lacus tincidunt. Phasellus a justo pharetra, accumsan lacus nec, laoreet diam. Donec vehicula ornare urna, eget imperdiet neque efficitur in. Nullam dolor metus, congue eget velit ut, dapibus dignissim nisl. Nullam varius in risus non faucibus.Quisque maximus erat id tristique vestibulum. Fusce eget ultrices sem, et egestas nibh. Pellentesque dignissim dui vel dui fringilla fringilla lobortis in tellus. Pellentesque egestas volutpat nulla, ut rhoncus velit. Phasellus molestie ligula nec pharetra feugiat. Suspendisse accumsan, ligula vel egestas pretium, arcu quam pulvinar turpis, et interdum est sapien sed augue. Duis in dictum nunc, et molestie metus. Aliquam erat volutpat. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;
                      Maecenas rhoncus, magna non facilisis luctus, enim ipsum cursus felis, ac rhoncus nulla massa a mi. Mauris placerat enim malesuada elit ultricies, a faucibus tortor efficitur. Ut quis purus eu augue tincidunt sodales. Suspendisse gravida id purus condimentum vehicula. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nullam nunc augue, pharetra ut libero non, facilisis rutrum nisi. Duis eget cursus ex, id malesuada justo. Vivamus eget massa tincidunt, vehicula enim ac, viverra nisi. Phasellus vulputate tellus felis, non tempor ligula facilisis quis. Pellentesque tincidunt iaculis enim, sit amet tristique libero finibus a. Etiam dui turpis, sagittis vestibulum interdum non, mollis id lorem. In non nisl ex. In eu ante ipsum. Curabitur fermentum a odio in lacinia. Integer rhoncus libero at odio rhoncus, ac ornare metus elementum. Fusce placerat porta felis, consectetur dictum nisl malesuada vitae.
                      Donec facilisis sapien libero. Duis nec varius ante. Duis non massa malesuada, iaculis erat eget, pretium leo. Nulla scelerisque volutpat turpis. In blandit ultricies nunc, ac finibus mauris feugiat porttitor. Integer pulvinar eros eu massa faucibus, nec rhoncus urna vestibulum. Nulla felis lectus, maximus ac viverra in, condimentum at felis. Donec vitae sodales nisi, sit amet efficitur risus. Vestibulum at finibus erat. Donec ante arcu, congue ut malesuada ut, fermentum ac ante. Morbi tristique condimentum sapien eget lobortis. Aenean pharetra pulvinar mauris, nec euismod neque accumsan non. Nulla sagittis leo quis diam lobortis auctor.
                      Aenean rhoncus vehicula lorem vel egestas. Nunc volutpat dui ac lacus lobortis, vitae tincidunt ipsum condimentum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vestibulum interdum ex lectus, sed aliquam dui pellentesque vitae. Vivamus vehicula convallis ultrices. Praesent eleifend, orci ac hendrerit cursus, ante lorem egestas erat, aliquam pulvinar lorem purus a elit. Fusce placerat urna fringilla mattis luctus. Aenean viverra porttitor lacus, quis placerat purus fermentum et. Pellentesque ac enim convallis, mattis eros id, finibus dui. Integer facilisis metus id consectetur tristique. Morbi semper urna pretium, finibus odio at, dapibus tellus. Aliquam commodo vitae quam ac bibendum. Quisque at neque pharetra, mollis ante a, faucibus massa. Ut accumsan, elit malesuada eleifend egestas, tortor erat blandit lorem, nec molestie dui nibh in sapien. In hac habitasse platea dictumst.''',
        'permalink': 'python-flask',
        'tags': 'python, flask, programming, coding, programmer'
    },
    {
        'title':'Top 10 websites to stream movies',
        'author': 'Tom Hanks',
        'content': '''Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent sit amet cursus lorem. Vestibulum massa tortor, fermentum et suscipit in, consectetur id nunc. Pellentesque ut odio cursus, varius neque ac, luctus felis. Duis vel nunc id erat condimentum interdum in nec velit. Aenean pharetra et risus vel consectetur. Suspendisse dignissim vehicula justo, non sodales felis dictum tincidunt. Phasellus faucibus diam ut mi euismod, ut aliquet lacus tincidunt. Phasellus a justo pharetra, accumsan lacus nec, laoreet diam. Donec vehicula ornare urna, eget imperdiet neque efficitur in. Nullam dolor metus, congue eget velit ut, dapibus dignissim nisl. Nullam varius in risus non faucibus.Quisque maximus erat id tristique vestibulum. Fusce eget ultrices sem, et egestas nibh. Pellentesque dignissim dui vel dui fringilla fringilla lobortis in tellus. Pellentesque egestas volutpat nulla, ut rhoncus velit. Phasellus molestie ligula nec pharetra feugiat. Suspendisse accumsan, ligula vel egestas pretium, arcu quam pulvinar turpis, et interdum est sapien sed augue. Duis in dictum nunc, et molestie metus. Aliquam erat volutpat. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;
                      Maecenas rhoncus, magna non facilisis luctus, enim ipsum cursus felis, ac rhoncus nulla massa a mi. Mauris placerat enim malesuada elit ultricies, a faucibus tortor efficitur. Ut quis purus eu augue tincidunt sodales. Suspendisse gravida id purus condimentum vehicula. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nullam nunc augue, pharetra ut libero non, facilisis rutrum nisi. Duis eget cursus ex, id malesuada justo. Vivamus eget massa tincidunt, vehicula enim ac, viverra nisi. Phasellus vulputate tellus felis, non tempor ligula facilisis quis. Pellentesque tincidunt iaculis enim, sit amet tristique libero finibus a. Etiam dui turpis, sagittis vestibulum interdum non, mollis id lorem. In non nisl ex. In eu ante ipsum. Curabitur fermentum a odio in lacinia. Integer rhoncus libero at odio rhoncus, ac ornare metus elementum. Fusce placerat porta felis, consectetur dictum nisl malesuada vitae.
                      Donec facilisis sapien libero. Duis nec varius ante. Duis non massa malesuada, iaculis erat eget, pretium leo. Nulla scelerisque volutpat turpis. In blandit ultricies nunc, ac finibus mauris feugiat porttitor. Integer pulvinar eros eu massa faucibus, nec rhoncus urna vestibulum. Nulla felis lectus, maximus ac viverra in, condimentum at felis. Donec vitae sodales nisi, sit amet efficitur risus. Vestibulum at finibus erat. Donec ante arcu, congue ut malesuada ut, fermentum ac ante. Morbi tristique condimentum sapien eget lobortis. Aenean pharetra pulvinar mauris, nec euismod neque accumsan non. Nulla sagittis leo quis diam lobortis auctor.
                      Aenean rhoncus vehicula lorem vel egestas. Nunc volutpat dui ac lacus lobortis, vitae tincidunt ipsum condimentum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vestibulum interdum ex lectus, sed aliquam dui pellentesque vitae. Vivamus vehicula convallis ultrices. Praesent eleifend, orci ac hendrerit cursus, ante lorem egestas erat, aliquam pulvinar lorem purus a elit. Fusce placerat urna fringilla mattis luctus. Aenean viverra porttitor lacus, quis placerat purus fermentum et. Pellentesque ac enim convallis, mattis eros id, finibus dui. Integer facilisis metus id consectetur tristique. Morbi semper urna pretium, finibus odio at, dapibus tellus. Aliquam commodo vitae quam ac bibendum. Quisque at neque pharetra, mollis ante a, faucibus massa. Ut accumsan, elit malesuada eleifend egestas, tortor erat blandit lorem, nec molestie dui nibh in sapien. In hac habitasse platea dictumst.''',
        'permalink': 'top-10-movies',
        'tags': 'movies, list, streaming, action'
    },
]